---

- name: User push to environment servers
  hosts: servers
  vars:
  gather_facts: True
  become: True
  tasks:

  - name: Debug env variables just to see them
    debug:
      var: env

  - name: Create the prod_engineer user
    user:
      name: prod_engineer
      comment: Prod engineer 
    when: '"prod" in env'

  - name: Create the dev_engineer user and give admin
    user:
      name: dev_engineer
      comment: Dev engineer
      groups: admin
    when: '"dev" in env'

